package com.transporte_gomez.erp.dto;

import lombok.Data;

@Data
public class DocumentoFiltro {

    private Long usuarioId;
    private Long numero;
    private Integer tipoCodigo;
    private String tipoNombre;
    private String fechaCreacionDesde;
    private String fechaCreacionHasta;

    // Constructor, getters, setters, etc. can be generated by Lombok
}
